In [27]:
import pandas as pd
import numpy as np

In [3]:
games = pd.read_csv("games.csv")
print(games)

      GAME_DATE_EST   GAME_ID GAME_STATUS_TEXT  HOME_TEAM_ID  VISITOR_TEAM_ID  \
0        2022-12-22  22200477            Final    1610612740       1610612759
1        2022-12-22  22200478            Final    1610612762       1610612764
2        2022-12-21  22200466            Final    1610612739       1610612749
3        2022-12-21  22200467            Final    1610612755       1610612765
4        2022-12-21  22200468            Final    1610612737       1610612741
...             ...       ...              ...           ...              ...
26646    2014-10-06  11400007            Final    1610612737       1610612740
26647    2014-10-06  11400004            Final    1610612741       1610612764
26648    2014-10-06  11400005            Final    1610612747       1610612743
26649    2014-10-05  11400002            Final    1610612761       1610612758
26650    2014-10-04  11400001            Final    1610612748       1610612740

       SEASON  TEAM_ID_home  PTS_home  FG_PCT_home  FT_PCT_home  ...  \
0        2022    1610612740     126.0        0.484        0.926  ...
1        2022    1610612762     120.0        0.488        0.952  ...
2        2022    1610612739     114.0        0.482        0.786  ...
3        2022    1610612755     113.0        0.441        0.909  ...
4        2022    1610612737     108.0        0.429        1.000  ...
...       ...           ...       ...          ...          ...  ...
26646    2014    1610612737      93.0        0.419        0.821  ...
26647    2014    1610612741      81.0        0.338        0.719  ...
26648    2014    1610612747      98.0        0.448        0.682  ...
26649    2014    1610612761      99.0        0.440        0.771  ...
26650    2014    1610612748      86.0        0.431        0.679  ...

       AST_home  REB_home  TEAM_ID_away  PTS_away  FG_PCT_away  FT_PCT_away  \
0          25.0      46.0    1610612759     117.0        0.478        0.815
1          16.0      40.0    1610612764     112.0        0.561        0.765
2          22.0      37.0    1610612749     106.0        0.470        0.682
3          27.0      49.0    1610612765      93.0        0.392        0.735
4          22.0      47.0    1610612741     110.0        0.500        0.773
...         ...       ...           ...       ...          ...          ...
26646      24.0      50.0    1610612740      87.0        0.366        0.643
26647      18.0      40.0    1610612764      85.0        0.411        0.636
26648      29.0      45.0    1610612743      95.0        0.387        0.659
26649      21.0      30.0    1610612758      94.0        0.469        0.725
26650      18.0      42.0    1610612740      98.0        0.462        0.706

       FG3_PCT_away  AST_away  REB_away  HOME_TEAM_WINS
0             0.321      23.0      44.0               1
1             0.333      20.0      37.0               1
2             0.433      20.0      46.0               1
3             0.261      15.0      46.0               1
4             0.292      20.0      47.0               0
...             ...       ...       ...             ...
26646         0.375      17.0      43.0               1
26647         0.267      17.0      47.0               0
26648         0.500      19.0      43.0               1
26649         0.385      18.0      45.0               1
26650         0.438      19.0      42.0               0

[26651 rows x 21 columns]

In [4]:
games.describe()

,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
count,2.665100e+04,2.665100e+04,2.665100e+04,26651.000000,2.665100e+04,26552.000000,26552.000000,26552.000000,26552.000000,26552.000000,26552.000000,2.665100e+04,26552.000000,26552.000000,26552.000000,26552.000000,26552.000000,26552.000000,26651.000000
mean,2.175487e+07,1.610613e+09,1.610613e+09,2012.113879,1.610613e+09,103.455898,0.460735,0.760377,0.356023,22.823441,43.374284,1.610613e+09,100.639876,0.449732,0.758816,0.349489,21.496271,42.113249,0.587032
std,5.570189e+06,8.638670e+00,8.659299e+00,5.587031,8.638670e+00,13.283370,0.056676,0.100677,0.111164,5.193308,6.625769,8.659299e+00,13.435868,0.055551,0.103429,0.109441,5.160596,6.533039,0.492376
min,1.030000e+07,1.610613e+09,1.610613e+09,2003.000000,1.610613e+09,36.000000,0.250000,0.143000,0.000000,6.000000,15.000000,1.610613e+09,33.000000,0.244000,0.143000,0.000000,4.000000,19.000000,0.000000
25%,2.070001e+07,1.610613e+09,1.610613e+09,2007.000000,1.610613e+09,94.000000,0.422000,0.697000,0.286000,19.000000,39.000000,1.610613e+09,91.000000,0.412000,0.692000,0.278000,18.000000,38.000000,0.000000
50%,2.120076e+07,1.610613e+09,1.610613e+09,2012.000000,1.610613e+09,103.000000,0.460000,0.765000,0.357000,23.000000,43.000000,1.610613e+09,100.000000,0.449000,0.765000,0.350000,21.000000,42.000000,1.000000
75%,2.180005e+07,1.610613e+09,1.610613e+09,2017.000000,1.610613e+09,112.000000,0.500000,0.833000,0.429000,26.000000,48.000000,1.610613e+09,110.000000,0.487000,0.833000,0.419000,25.000000,46.000000,1.000000
max,5.210021e+07,1.610613e+09,1.610613e+09,2022.000000,1.610613e+09,168.000000,0.684000,1.000000,1.000000,50.000000,72.000000,1.610613e+09,168.000000,0.687000,1.000000,1.000000,46.000000,81.000000,1.000000

In [6]:
games.shape # shows no of rows and cols in dataset

(26651, 21)

In [8]:
games.isnull().sum()  # count of the null values in each column in dataset

GAME_DATE_EST        0
GAME_ID              0
GAME_STATUS_TEXT     0
HOME_TEAM_ID         0
VISITOR_TEAM_ID      0
SEASON               0
TEAM_ID_home         0
PTS_home            99
FG_PCT_home         99
FT_PCT_home         99
FG3_PCT_home        99
AST_home            99
REB_home            99
TEAM_ID_away         0
PTS_away            99
FG_PCT_away         99
FT_PCT_away         99
FG3_PCT_away        99
AST_away            99
REB_away            99
HOME_TEAM_WINS       0
dtype: int64

In [10]:
games[games.isnull().any(axis=1)]["GAME_STATUS_TEXT"].value_counts() #counts the missing row values in game_status_text col

GAME_STATUS_TEXT
Final    99
Name: count, dtype: int64

In [12]:
games = games.dropna(subset=["PTS_home", "PTS_away"])
games.isnull().sum()

GAME_DATE_EST       0
GAME_ID             0
GAME_STATUS_TEXT    0
HOME_TEAM_ID        0
VISITOR_TEAM_ID     0
SEASON              0
TEAM_ID_home        0
PTS_home            0
FG_PCT_home         0
FT_PCT_home         0
FG3_PCT_home        0
AST_home            0
REB_home            0
TEAM_ID_away        0
PTS_away            0
FG_PCT_away         0
FT_PCT_away         0
FG3_PCT_away        0
AST_away            0
REB_away            0
HOME_TEAM_WINS      0
dtype: int64

In [13]:
games.duplicated(subset=["GAME_ID"]).sum()

np.int64(29)

In [14]:
games[games.duplicated(subset=["GAME_ID"], keep=False)].sort_values("GAME_ID").head(10)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
2535,2020-12-25,22000006,Final,1610612749,1610612744,2020,1610612749,138.0,0.556,0.692,...,25.0,60.0,1610612744,99.0,0.343,0.840,0.222,14.0,43.0,1
3125,2020-12-25,22000006,Final,1610612749,1610612744,2020,1610612749,138.0,0.556,0.692,...,25.0,60.0,1610612744,99.0,0.343,0.840,0.222,14.0,43.0,1
3126,2020-12-25,22000007,Final,1610612738,1610612751,2020,1610612738,95.0,0.378,0.684,...,23.0,47.0,1610612751,123.0,0.539,0.839,0.517,21.0,43.0,0
2536,2020-12-25,22000007,Final,1610612738,1610612751,2020,1610612738,95.0,0.378,0.684,...,23.0,47.0,1610612751,123.0,0.539,0.839,0.517,21.0,43.0,0
2540,2020-12-23,22000011,Final,1610612754,1610612752,2020,1610612754,121.0,0.489,0.724,...,28.0,50.0,1610612752,107.0,0.459,0.739,0.429,25.0,40.0,1
3127,2020-12-23,22000011,Final,1610612754,1610612752,2020,1610612754,121.0,0.489,0.724,...,28.0,50.0,1610612752,107.0,0.459,0.739,0.429,25.0,40.0,1
3128,2020-12-23,22000013,Final,1610612755,1610612764,2020,1610612755,113.0,0.471,0.767,...,22.0,47.0,1610612764,107.0,0.459,0.696,0.481,28.0,40.0,1
2542,2020-12-23,22000013,Final,1610612755,1610612764,2020,1610612755,113.0,0.471,0.767,...,22.0,47.0,1610612764,107.0,0.459,0.696,0.481,28.0,40.0,1
2545,2020-12-23,22000015,Final,1610612741,1610612737,2020,1610612741,104.0,0.414,0.857,...,20.0,37.0,1610612737,124.0,0.538,0.828,0.400,24.0,46.0,0
3129,2020-12-23,22000015,Final,1610612741,1610612737,2020,1610612741,104.0,0.414,0.857,...,20.0,37.0,1610612737,124.0,0.538,0.828,0.400,24.0,46.0,0

In [16]:
games = games.drop_duplicates(subset=["GAME_ID"], keep="first")
games.duplicated(subset=["GAME_ID"]).sum()

np.int64(0)

In [17]:
games["GAME_DATE_EST"].dtype

dtype('O')

In [18]:
games["GAME_DATE_EST"].head()

0    2022-12-22
1    2022-12-22
2    2022-12-21
3    2022-12-21
4    2022-12-21
Name: GAME_DATE_EST, dtype: object

In [19]:
games.describe()

,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
count,2.652300e+04,2.652300e+04,2.652300e+04,26523.000000,2.652300e+04,26523.000000,26523.000000,26523.000000,26523.000000,26523.00000,26523.000000,2.652300e+04,26523.000000,26523.000000,26523.000000,26523.000000,26523.000000,26523.000000,26523.000000
mean,2.179736e+07,1.610613e+09,1.610613e+09,2012.139275,1.610613e+09,103.449157,0.460751,0.760409,0.356052,22.82140,43.370509,1.610613e+09,100.629039,0.449723,0.758815,0.349467,21.493836,42.109754,0.589224
std,5.539413e+06,8.641271e+00,8.658665e+00,5.566584,8.641271e+00,13.280884,0.056676,0.100651,0.111180,5.19289,6.624297,8.658665e+00,13.431869,0.055556,0.103392,0.109452,5.161328,6.532954,0.491984
min,1.030000e+07,1.610613e+09,1.610613e+09,2003.000000,1.610613e+09,36.000000,0.250000,0.143000,0.000000,6.00000,15.000000,1.610613e+09,33.000000,0.244000,0.143000,0.000000,4.000000,19.000000,0.000000
25%,2.070008e+07,1.610613e+09,1.610613e+09,2007.000000,1.610613e+09,94.000000,0.422000,0.697000,0.286000,19.00000,39.000000,1.610613e+09,91.000000,0.412000,0.692000,0.278000,18.000000,38.000000,0.000000
50%,2.120080e+07,1.610613e+09,1.610613e+09,2012.000000,1.610613e+09,103.000000,0.460000,0.765000,0.357000,23.00000,43.000000,1.610613e+09,100.000000,0.449000,0.765000,0.350000,21.000000,42.000000,1.000000
75%,2.180005e+07,1.610613e+09,1.610613e+09,2017.000000,1.610613e+09,112.000000,0.500000,0.833000,0.429000,26.00000,48.000000,1.610613e+09,110.000000,0.487000,0.833000,0.419000,25.000000,46.000000,1.000000
max,5.210021e+07,1.610613e+09,1.610613e+09,2022.000000,1.610613e+09,168.000000,0.684000,1.000000,1.000000,50.00000,72.000000,1.610613e+09,168.000000,0.687000,1.000000,1.000000,46.000000,81.000000,1.000000

In [21]:
games["GAME_DATE_EST"] = pd.to_datetime(games["GAME_DATE_EST"])
games["GAME_DATE_EST"].dtype

dtype('<M8[ns]')

In [24]:
(games["HOME_TEAM_ID"] == games["TEAM_ID_home"]).all()
(games["VISITOR_TEAM_ID"] == games["TEAM_ID_away"]).all()

np.True_

In [34]:
games["TOTAL_POINTS"] = games["PTS_home"] + games["PTS_away"]
games["WIN_TYPE"] = np.where(
    games["HOME_TEAM_WINS"] == 1,
    "Home Win",
    "Away Win"
)


games = games.rename(columns={
    "GAME_ID": "game_id",
    "GAME_DATE_EST": "game_date",
    "HOME_TEAM_ID": "home_team_id",
    "VISITOR_TEAM_ID": "away_team_id",
    "PTS_home": "pts_home",
    "PTS_away": "pts_away",
    "HOME_TEAM_WINS": "home_team_wins",
    "TOTAL_POINTS": "total_points",
    "WIN_TYPE": "win_type",
    "SEASON": "season"
})

In [33]:
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql+psycopg2://postgres:"password"@localhost:"portnumber"/nba_analysis"
)

In [35]:
games.to_sql(
    "games",
    engine,
    if_exists="replace",
    index=False
)

523