In [1]:
import pandas as pd

In [3]:
players = pd.read_csv("players.csv")
players.describe()

            TEAM_ID     PLAYER_ID       SEASON
count  7.228000e+03  7.228000e+03  7228.000000
mean   1.610613e+09  2.355862e+06  2014.159934
std    8.723521e+00  6.106688e+07     3.126216
min    1.610613e+09  2.440000e+02  2009.000000
25%    1.610613e+09  2.007680e+05  2012.000000
50%    1.610613e+09  2.023465e+05  2014.000000
75%    1.610613e+09  2.039100e+05  2017.000000
max    1.610613e+09  1.962938e+09  2019.000000

In [4]:
players.shape

(7228, 4)

In [5]:
players.isnull().sum()

PLAYER_NAME    0
TEAM_ID        0
PLAYER_ID      0
SEASON         0
dtype: int64

In [6]:
players.duplicated(subset=["PLAYER_ID", "SEASON"]).sum()

np.int64(923)

In [8]:
players[players.duplicated(subset=["PLAYER_ID", "SEASON"], keep=False)].head(10)

                 PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
62                 Max Strus  1610612741    1629622    2019
145           Tyrone Wallace  1610612737    1627820    2019
286           Shamorie Ponds  1610612761    1629044    2019
382         Alfonzo McKinnie  1610612739    1628035    2019
389  Timothe Luwawu-Cabarrot  1610612751    1627789    2019
416          DaQuan Jeffries  1610612758    1629610    2019
420               Tyler Cook  1610612739    1629076    2019
491           Shamorie Ponds  1610612745    1629044    2019
492             Ray Spalding  1610612745    1629034    2019
520         Alfonzo McKinnie  1610612744    1628035    2019

In [9]:
players = players.drop_duplicates(subset=["PLAYER_ID", "SEASON"], keep="first")
players.duplicated(subset=["PLAYER_ID", "SEASON"]).sum()

np.int64(0)

In [10]:
players = players[["PLAYER_ID", "PLAYER_NAME", "SEASON"]]
players.head()

   PLAYER_ID       PLAYER_NAME  SEASON
0    1626220     Royce O'Neale    2019
1     202711  Bojan Bogdanovic    2019
2     203497       Rudy Gobert    2019
3    1628378  Donovan Mitchell    2019
4     201144       Mike Conley    2019

In [11]:
players = players.rename(columns={
    "PLAYER_ID": "player_id",
    "PLAYER_NAME": "player_name",
    "SEASON": "season"
})

In [14]:
from sqlalchemy import create_engine
engine = create_engine("postgresql+psycopg2://postgres:"password"@localhost:"portnumber"/nba_analysis")
players.to_sql("players", engine, if_exists="replace",index=False)

305

In [15]:
players.shape

(6305, 3)